USE farmers_market_db;

INSERT INTO `users` (`user_id`, `user_name`, `user_type`, `created_by`) VALUES
    ('1', 'Cordy Donn', 'farmer', 'mockaroo'),
    ('2', 'Ferd Reddan', 'farmer', 'mockaroo'),
    ('3', 'Gris Brevetor', 'farmer', 'mockaroo'),
    ('4', 'Odessa Maidens', 'farmer', 'mockaroo'),
    ('5', 'Averil Hardwich', 'farmer', 'mockaroo'),
    ('6', 'Arlee Hulance', 'farmer', 'mockaroo'),
    ('7', 'Reagan Simonsen', 'farmer', 'mockaroo'),
    ('8', 'Felita Cockley', 'farmer', 'mockaroo'),
    ('9', 'Elle Brice', 'farmer', 'mockaroo'),
    ('10', 'Wadsworth Di Domenico', 'farmer', 'mockaroo'),
    ('11', 'Hugo Jakubiak', 'farmer', 'mockaroo'),
    ('12', 'Leonhard Caston', 'farmer', 'mockaroo'),
    ('13', 'Marna Lexa', 'farmer', 'mockaroo'),
    ('14', 'Waylon Rawet', 'farmer', 'mockaroo'),
    ('15', 'Sandor Tax', 'farmer', 'mockaroo'),
    ('16', 'Sidnee Flanaghan', 'farmer', 'mockaroo'),
    ('17', 'Laurena Wilderspoon', 'farmer', 'mockaroo'),
    ('18', 'Sissy Golston', 'farmer', 'mockaroo'),
    ('19', 'Sibley Worgen', 'farmer', 'mockaroo'),
    ('20', 'Janifer Davitashvili', 'farmer', 'mockaroo'),
    ('21', 'Eryn Nelle', 'farmer', 'mockaroo'),
    ('22', 'Lisette Craise', 'farmer', 'mockaroo'),
    ('23', 'Lawry Hutchason', 'farmer', 'mockaroo'),
    ('24', 'Patten Aizikovich', 'farmer', 'mockaroo'),
    ('25', 'Jodi Reidie', 'farmer', 'mockaroo'),
    ('26', 'Wilmer Kirkham', 'farmer', 'mockaroo'),
    ('27', 'Jefferson Tomblett', 'farmer', 'mockaroo'),
    ('28', 'Clemmie Casaroli', 'farmer', 'mockaroo'),
    ('29', 'Ronny Figurski', 'farmer', 'mockaroo'),
    ('30', 'Torrance St. Hill', 'farmer', 'mockaroo'),
    ('31', 'Lyssa Fries', 'farmer', 'mockaroo'),
    ('32', 'Garner Marini', 'farmer', 'mockaroo'),
    ('33', 'Rahel Franssen', 'farmer', 'mockaroo'),
    ('34', 'Merci Pill', 'farmer', 'mockaroo'),
    ('35', 'Gabriel Proby', 'farmer', 'mockaroo'),
    ('36', 'Cull Gard', 'farmer', 'mockaroo'),
    ('37', 'Prentiss Krammer', 'farmer', 'mockaroo'),
    ('38', 'Edi Limbert', 'farmer', 'mockaroo'),
    ('39', 'Meier Dormand', 'farmer', 'mockaroo'),
    ('40', 'Evania Gelardi', 'farmer', 'mockaroo'),
    ('41', 'Jenifer Hodgin', 'farmer', 'mockaroo'),
    ('42', 'Travers Arson', 'farmer', 'mockaroo'),
    ('43', 'Dreddy Gummow', 'farmer', 'mockaroo'),
    ('44', 'Avigdor Saiger', 'farmer', 'mockaroo'),
    ('45', 'Leyla Dadson', 'farmer', 'mockaroo'),
    ('46', 'Haily Ballintime', 'farmer', 'mockaroo'),
    ('47', 'Shannon Beeho', 'farmer', 'mockaroo'),
    ('48', 'Sig Mattholie', 'farmer', 'mockaroo'),
    ('49', 'Kaleb Lowes', 'farmer', 'mockaroo'),
    ('50', 'Ransell De Michetti', 'farmer', 'mockaroo'),
    ('51', 'Jalen Brunson', 'politician', 'mockaroo'),
    ('52', 'Daveta Jackson', 'researcher', 'mockaroo'),
    ('53', 'Danit Todd', 'researcher', 'mockaroo'),
    ('54', 'Gery Matthews', 'researcher', 'mockaroo'),
    ('55', 'Maureene Sung', 'researcher', 'mockaroo'),
    ('56', 'Cathryn Garcia', 'researcher', 'mockaroo'),
    ('57', 'Anita Boniface', 'researcher', 'mockaroo'),
    ('58', 'Theresa James', 'politician', 'mockaroo'),
    ('59', 'Elena Cobbler', 'politician', 'mockaroo'),
    ('60', 'Davina Liu', 'politician', 'mockaroo'),
    ('61', 'Pascale Lopez', 'politician', 'mockaroo'),
    ('62', 'Willie Ryan', 'researcher', 'mockaroo'),
    ('63', 'Jenn Laurence', 'politician', 'mockaroo'),
    ('64', 'Ker Smith', 'researcher', 'mockaroo'),
    ('65', 'Janine Scotti', 'politician', 'mockaroo'),
    ('66', 'Liz Beth', 'politician', 'mockaroo'),
    ('67', 'OG Anunoby', 'politician', 'mockaroo'),
    ('68', 'Meghan Fox', 'researcher', 'mockaroo'),
    ('69', 'Colan Kim', 'politician', 'mockaroo'),
    ('70', 'Jeanna Singh', 'researcher', 'mockaroo'),
    ('71', 'Devlin Dolan', 'politician', 'mockaroo'),
    ('72', 'Roland Patel', 'politician', 'mockaroo'),
    ('73', 'Hilliard Habib', 'politician', 'mockaroo'),
    ('74', 'Margaux Bompelli', 'researcher', 'mockaroo'),
    ('75', 'Sayers Li', 'researcher', 'mockaroo');

-- Mock discussion board posts, replies, and reactions

-- Posts: two per persona (farmers, politicians, researchers)
INSERT INTO `posts` (post_id, title, post_text, user_id, created_by) VALUES
(1, 'Planting schedule tips for spring', 'Any tips for adjusting planting schedules with unpredictable rainfall?', 1, 'mockaroo'),
(2, 'Best compost mixtures?', 'I''ve been mixing compost with wood chips; any recommendations?', 2, 'mockaroo'),
(3, 'Proposed subsidy for smallholders', 'We propose targeted subsidies for water-efficient irrigation systems. Thoughts?', 51, 'mockaroo'),
(4, 'Market regulation impact study', 'How will price caps affect small farmers in rural areas?', 58, 'mockaroo'),
(5, 'Soil moisture sensors dataset available', 'I collected soil moisture data across 10 farms; sharing methodology and results.', 52, 'mockaroo'),
(6, 'New crop yield model draft', 'I''m testing a simple ML model for predicting yields based on NPK and rainfall.', 62, 'mockaroo');

-- Comments (replies) to the above posts
INSERT INTO `comments` (comment_id, texts, post_id, user_id, created_by) VALUES
(1, 'I''ve had good results starting seedlings indoors 2 weeks earlier.', 1, 3, 'mockaroo'),
(2, 'Try adding more nitrogen in early growth stages.', 1, 4, 'mockaroo'),
(3, 'Have you considered vermicompost? Works well.', 2, 5, 'mockaroo'),
(4, 'We support the subsidy; it would help modernize irrigation.', 3, 59, 'mockaroo'),
(5, 'There may be unintended consequences; needs pilot testing.', 3, 52, 'mockaroo'),
(6, 'Price caps could discourage supply; maybe targeted vouchers instead.', 4, 51, 'mockaroo'),
(7, 'I can share the dataset and preprocessing steps.', 5, 70, 'mockaroo'),
(8, 'Can you publish the model code? Would like to reproduce.', 6, 74, 'mockaroo');

-- Reactions: likes (pos_neg=1) and dislikes (pos_neg=0)
INSERT INTO `reactions` (reaction_id, pos_neg, post_id, user_id, created_by) VALUES
(1, 1, 1, 10, 'mockaroo'),
(2, 1, 1, 2, 'mockaroo'),
(3, 0, 1, 15, 'mockaroo'),
(4, 1, 3, 58, 'mockaroo'),
(5, 1, 3, 62, 'mockaroo'),
(6, 0, 4, 16, 'mockaroo'),
(7, 1, 5, 52, 'mockaroo'),
(8, 1, 6, 74, 'mockaroo'),
(9, 0, 6, 23, 'mockaroo');