USE farmers_market_db;

INSERT INTO `users` (`user_id`, `user_name`, `user_type`, `created_by`) VALUES
    ('1', 'Cordy Donn', 'farmer', 'mockaroo'),
    ('2', 'Ferd Reddan', 'farmer', 'mockaroo'),
    ('3', 'Gris Brevetor', 'farmer', 'mockaroo'),
    ('4', 'Odessa Maidens', 'farmer', 'mockaroo'),
    ('5', 'Averil Hardwich', 'farmer', 'mockaroo'),
    ('6', 'Arlee Hulance', 'farmer', 'mockaroo'),
    ('7', 'Reagan Simonsen', 'farmer', 'mockaroo'),
    ('8', 'Felita Cockley', 'farmer', 'mockaroo'),
    ('9', 'Elle Brice', 'farmer', 'mockaroo'),
    ('10', 'Wadsworth Di Domenico', 'farmer', 'mockaroo'),
    ('11', 'Hugo Jakubiak', 'farmer', 'mockaroo'),
    ('12', 'Leonhard Caston', 'farmer', 'mockaroo'),
    ('13', 'Marna Lexa', 'farmer', 'mockaroo'),
    ('14', 'Waylon Rawet', 'farmer', 'mockaroo'),
    ('15', 'Sandor Tax', 'farmer', 'mockaroo'),
    ('16', 'Sidnee Flanaghan', 'farmer', 'mockaroo'),
    ('17', 'Laurena Wilderspoon', 'farmer', 'mockaroo'),
    ('18', 'Sissy Golston', 'farmer', 'mockaroo'),
    ('19', 'Sibley Worgen', 'farmer', 'mockaroo'),
    ('20', 'Janifer Davitashvili', 'farmer', 'mockaroo'),
    ('21', 'Eryn Nelle', 'farmer', 'mockaroo'),
    ('22', 'Lisette Craise', 'farmer', 'mockaroo'),
    ('23', 'Lawry Hutchason', 'farmer', 'mockaroo'),
    ('24', 'Patten Aizikovich', 'farmer', 'mockaroo'),
    ('25', 'Jodi Reidie', 'farmer', 'mockaroo'),
    ('26', 'Wilmer Kirkham', 'farmer', 'mockaroo'),
    ('27', 'Jefferson Tomblett', 'farmer', 'mockaroo'),
    ('28', 'Clemmie Casaroli', 'farmer', 'mockaroo'),
    ('29', 'Ronny Figurski', 'farmer', 'mockaroo'),
    ('30', 'Torrance St. Hill', 'farmer', 'mockaroo'),
    ('31', 'Lyssa Fries', 'farmer', 'mockaroo'),
    ('32', 'Garner Marini', 'farmer', 'mockaroo'),
    ('33', 'Rahel Franssen', 'farmer', 'mockaroo'),
    ('34', 'Merci Pill', 'farmer', 'mockaroo'),
    ('35', 'Gabriel Proby', 'farmer', 'mockaroo'),
    ('36', 'Cull Gard', 'farmer', 'mockaroo'),
    ('37', 'Prentiss Krammer', 'farmer', 'mockaroo'),
    ('38', 'Edi Limbert', 'farmer', 'mockaroo'),
    ('39', 'Meier Dormand', 'farmer', 'mockaroo'),
    ('40', 'Evania Gelardi', 'farmer', 'mockaroo'),
    ('41', 'Jenifer Hodgin', 'farmer', 'mockaroo'),
    ('42', 'Travers Arson', 'farmer', 'mockaroo'),
    ('43', 'Dreddy Gummow', 'farmer', 'mockaroo'),
    ('44', 'Avigdor Saiger', 'farmer', 'mockaroo'),
    ('45', 'Leyla Dadson', 'farmer', 'mockaroo'),
    ('46', 'Haily Ballintime', 'farmer', 'mockaroo'),
    ('47', 'Shannon Beeho', 'farmer', 'mockaroo'),
    ('48', 'Sig Mattholie', 'farmer', 'mockaroo'),
    ('49', 'Kaleb Lowes', 'farmer', 'mockaroo'),
    ('50', 'Ransell De Michetti', 'farmer', 'mockaroo'),
    ('51', 'Ker', 'politician', 'mockaroo'),
    ('52', 'Daveta', 'researcher', 'mockaroo'),
    ('53', 'Danit', 'researcher', 'mockaroo'),
    ('54', 'Gery', 'researcher', 'mockaroo'),
    ('55', 'Maureene', 'researcher', 'mockaroo'),
    ('56', 'Cathryn', 'researcher', 'mockaroo'),
    ('57', 'Boniface', 'researcher', 'mockaroo'),
    ('58', 'Theresa', 'politician', 'mockaroo'),
    ('59', 'Elena', 'politician', 'mockaroo'),
    ('60', 'Davina', 'politician', 'mockaroo'),
    ('61', 'Pascale', 'politician', 'mockaroo'),
    ('62', 'Willie', 'researcher', 'mockaroo'),
    ('63', 'Pascale', 'politician', 'mockaroo'),
    ('64', 'Chelsea', 'researcher', 'mockaroo'),
    ('65', 'Scotti', 'politician', 'mockaroo'),
    ('66', 'Liz', 'politician', 'mockaroo'),
    ('67', 'Emlyn', 'politician', 'mockaroo'),
    ('68', 'Ari', 'researcher', 'mockaroo'),
    ('69', 'Colan', 'politician', 'mockaroo'),
    ('70', 'Jeanna', 'researcher', 'mockaroo'),
    ('71', 'Devlin', 'politician', 'mockaroo'),
    ('72', 'Roland', 'politician', 'mockaroo'),
    ('73', 'Hilliard', 'politician', 'mockaroo'),
    ('74', 'Margaux', 'researcher', 'mockaroo'),
    ('75', 'Sayers', 'researcher', 'mockaroo');